inscape_dir = "D:/inscape_test/C0DA01/side_side_h0_s1-i0"
inscape_newdir = "D:/experimental/cutout/data/inscape"
dworld_dir = "D:/dworld"
dworld_newdir = "D:/experimental/cutout/data/dworld"
ng_dir_train = "train/NG"
ok_dir_train = "train/OK"
ng_dir_test = "test/NG"
ok_dir_test = "test/OK"

fruit_dir = r"D:\fresh_and_rotten_dataset"
fruit_newdir = "D:/experimental/cutout/data/fruits"
fresh_dir_train = "train/freshapples"
rot_dir_train = "train/rottenapples"
fresh_dir_test = "test/freshapples"
rot_dir_test = "test/rottenapples"