inscape_dir = "D:/inscape_test/C0DA01/side_side_h0_s1-i0"
inscape_newdir = "D:/experimental/cutout/data/inscape"
dworld_dir = "D:/dworld"
dworld_newdir = "D:/experimental/cutout/data/dworld"
ng_dir_train = "train/NG"
ok_dir_train = "train/OK"
ng_dir_test = "test/NG"
ok_dir_test = "test/OK"

fruit_dir = r"D:\fresh_and_rotten_dataset"
fruit_newdir = "D:/experimental/cutout/data/fruits"
fresh_dir_train = "train/freshapples"
rot_dir_train = "train/rottenapples"
fresh_dir_test = "test/freshapples"
rot_dir_test = "test/rottenapples"

hanrim_dir = "D:/hanrim_dataset"
hanrim_newdir = "D:/experimental/cutout/data/hanrim"

implant_dir = "D:/055_Dental Implant_3class_990ea_customer_200220"
implant_newdir = "D:/experimental/cutout/data/implant"
implant_D_train = "train/D"
implant_D_test = "test/D"
implant_I_train = "train/I"
implant_I_test = "test/I"
implant_O_train = "train/O"
implant_O_test = "test/O"

autoever_dir = "D:/autoever_2020-12-04/img"
autoever_newdir = "D:/experimental/cutout/data/autoever"
autoever_ok_train = "train/OK"
autoever_ok_test = "test/OK"
autoever_p1_train = "train/P1"
autoever_p1_test = "test/P1"
autoever_p2_train = "train/P2"
autoever_p2_test = "test/P2"

chest_dir = "D:/chest_xray/"
chest_newdir = "D:/experimental/cutout/data/xray"
chest_ok_train = "train/NORMAL"
chest_ng_train = "train/PNEUMONIA"
chest_ok_test = "test/NORMAL"
chest_ng_test = "test/PNEUMONIA"
